framework:
    rate_limiter:
        ajax_request:
            # use 'sliding_window' if you prefer that policy
            policy: 'fixed_window'
            limit: 10
            interval: '1 minutes'
        